- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/resumes_controller.rb
- app/controllers/users/omniauth_callbacks_controller.rb
- app/helpers/resumes_helper.rb
- app/models/resume.rb
- app/models/user.rb
- app/policies/user_policy.rb
- app/views/layouts/application.html.erb
- config/application.rb
- config/initializers/devise.rb
- config/locales/zh-TW.yml
- config/routes.rb
- db/migrate/20230813025852_drop_resume.rb
- db/migrate/20230813032450_create_resumes.rb
- db/schema.rb
- test/controllers/resumes_controller_test.rb
- test/fixtures/resumes.yml
- test/models/resume_test.rb
- test/policies/user_policy_test.rb
只有建立了 model 、 controller for 子禔
> [build]:Resume system

- .rubocop.yml
- Gemfile
- app/helpers/application_helper.rb
> [fix]: rubocop setting

- app/controllers/users_controller.rb
- app/views/users/select_role.html.erb
> [fix]: revised employer_path to  new_company_path

- app/controllers/users_controller.rb
- app/views/users/apply_job.html.erb
> [fix]: apply_job_time

- README.md
- app/assets/stylesheets/application.css
- app/controllers/job_matchings_controller.rb
- app/controllers/jobs_controller.rb
- app/models/job_matching.rb
- app/views/companies/edit.html.erb
- app/views/job_matchings/edit.html.erb
- app/views/jobs/_form.html.erb
- app/views/jobs/receive_application.html.erb
- app/views/profiles/show.html.erb
- app/views/users/apply_job.html.erb
- config/routes.rb
- db/migrate/20230903144321_add_interview_notification_to_job_matchings.rb
- db/schema.rb
- 求職者的應徵紀錄頁面可以觀看面試通知紀錄
- 雇主需選擇日期與時間、編輯面試訊息或直接以預設訊息寄送
- 雇主在發完面試通知會顯示 disabled 按鈕
> [build]:雇主發起面試通知的消息、求職者接收可以在應徵紀錄頁面收到消息

- app/assets/stylesheets/application.tailwind.css
- app/controllers/jobs_controller.rb
- app/controllers/resumes_controller.rb
- app/views/articles/show.html.erb
- app/views/jobs/index.html.erb
- app/views/jobs/receive_applicant.html.erb
- app/views/resumes/edit.html.erb
- app/views/resumes/index.html.erb
- app/views/resumes/show.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
修改Resume edit 的排版畫面
修改Resume show的排版畫面
> [style]: 修改Resume edit and show的排版畫面

- db/migrate/20230907042902_add_columns_to_resumes.rb
- db/migrate/20230907050738_add_reference_to_resumes.rb
- db/schema.rb
增加了resume欄位裡的基本資料，包含電話，地址，關於我，想要的職位
增加了resume對公司，教育程度，專案的關聯
> [build]: resume model

- app/assets/stylesheets/application.css
- app/javascript/controllers/notification_controller.js
- app/views/layouts/application.html.erb
- bin/dev
- config/importmap.rb
> [build]: 增加 Sweet Alert 功能

- app/views/jobs/index.html.erb
- 修正 index.html.erb/jobs 撈資訊的變數寫法
> [fix]: jobs index.html.erb line 12 @job_list change to @jobs

- app/controllers/users/omniauth_callbacks_controller.rb
- app/mailers/user_mailer.rb
- app/models/user.rb
- app/views/devise/mailer/confirmation_instructions.html.erb
- config/environments/development.rb
- config/environments/production.rb
- config/locales/zh-TW.yml
> [fix]: 修復 mailgun 認證信件

- app/assets/stylesheets/application.tailwind.css
- app/helpers/application_helper.rb
- app/javascript/controllers/navbar_controller.js
- app/views/pages/index.html.erb
- app/views/profiles/_show.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
- 漢堡選單功能修復
- 將導覽列的字體加粗
- 移除作品集連結
- 修正首頁的錯字與內容
> [fix]: 漢堡選單修復、修正首頁的錯字與內容、移除作品集連結

- app/views/users/select_role.html.erb
> [style]: select_role_rwd

- app/views/jobs/jobs_list.html.erb
修改了應徵之後 關閉"馬上應徵"的按鈕
https://github.com/astrocamp/14th-READMee/assets/138268474/32359408-29e9-4fc0-bbf4-3cd06ec2d4f8
> [fix]: before_job_matching_close_the_btn

- app/views/profiles/_show.html.erb
- app/views/users/apply_job.html.erb
RT
https://github.com/astrocamp/14th-READMee/assets/138268474/e64be409-3ed0-4af2-b7e5-a8d112f1cde4
> [fix]: 沒有應徵紀錄的話顯示"快去應徵吧!"

- app/controllers/companies_controller.rb
- app/views/users/apply_job.html.erb
> [fix]: 求職者要看公司的路徑錯誤

- app/controllers/resumes_controller.rb
- db/seeds.rb
> [build]: 建立使用者、公司、工作種子資料

- app/helpers/resumes_helper.rb
- app/helpers/work_experiences_helper.rb
- app/views/resumes/_area1.html.erb
- app/views/resumes/_show_area1.html.erb
> [fix]: transfer image to Base64 to fix the pdf function

- app/assets/stylesheets/application.css
- app/assets/stylesheets/application.tailwind.css
- app/models/resume.rb
- app/views/resumes/_area1.html.erb
- app/views/resumes/_area2.html.erb
- app/views/resumes/_area3.html.erb
- app/views/resumes/_area4.html.erb
- app/views/resumes/_show_area1.html.erb
- app/views/resumes/_show_area2.html.erb
- app/views/resumes/edit.html.erb
- app/views/resumes/index.html.erb
- app/views/resumes/show.html.erb
- app/views/users/dashboard.html.erb
> [style]: Resume style

- app/controllers/jobs_controller.rb
- app/views/jobs/jobs_list.html.erb
> [fix]: 修正了使用者無法正常進入工作職缺、建立公司後會取代掉其他工作職缺

- app/javascript/controllers/toggle_dark_mode_controller.js
- app/views/layouts/application.html.erb
> [fix] Toggle dark mode

- app/views/jobs/jobs_list.html.erb
> [fix]: 修正了公司可以看到應徵工作的按鈕

- app/assets/stylesheets/application.tailwind.css
- app/controllers/job_matchings_controller.rb
- app/controllers/resumes_controller.rb
- app/controllers/users_controller.rb
- app/helpers/application_helper.rb
- app/javascript/controllers/publish_controller.js
- app/javascript/controllers/unPublish_controller.js
- app/views/jobs/jobs_list.html.erb
- app/views/jobs/receive_applicant.html.erb
- app/views/profiles/_show.html.erb
- app/views/resumes/edit.html.erb
- app/views/resumes/show.html.erb
- app/views/shared/_navbar.html.erb
- app/views/social_link/_show.html.erb
- app/views/users/apply_job.html.erb
- app/views/users/dashboard.html.erb
- app/views/work_experiences/_show.html.erb
- 修正畫面的按鈕樣式、增加 notice 以及更新跑版畫面
> [fix]: add btn style and the notice

- app/assets/stylesheets/application.css
- app/controllers/resumes_controller.rb
- app/models/resume.rb
- app/views/resumes/_area1.html.erb
- app/views/resumes/_area2.html.erb
- app/views/resumes/_area3.html.erb
- app/views/resumes/_area4.html.erb
- app/views/resumes/edit.html.erb
> [style]: resume RWD

- app/assets/stylesheets/application.tailwind.css
- app/controllers/application_controller.rb
- app/controllers/jobs_controller.rb
- app/views/jobs/jobs_list.html.erb
- app/views/jobs/show.html.erb
RT
並且加上了判斷是否有應徵過
https://github.com/astrocamp/14th-READMee/assets/138268474/8bebc010-d72f-480d-9b8c-34aaab73b32f
> [fix]: 在 show jobs 的頁面 應徵失敗

- app/views/shared/_navbar.html.erb
> [fix]: 若使用者沒選擇身分，將會導向選擇身分的頁面

- app/views/profiles/_avatar_preview.html.erb
> [style]: fix file button style

- app/views/profiles/_show.html.erb
> [fix]: remove the extra in dashboard

- app/controllers/job_matchings_controller.rb
- app/views/job_matchings/edit.html.erb
> [fix]: job_matching

- app/views/articles/show.html.erb
- app/views/resumes/_area2.html.erb
- app/views/resumes/_area4.html.erb
修改resume edit   時間欄位的寬度以及文章留言cursor-pointer
> [style]:  修改resume edit時間欄位的寬度以及文章留言cursor-pointer

- app/views/companies/show.html.erb
> [style]: add_padding_show_company

- app/controllers/companies_controller.rb
> [fix]: new_company_bug

- app/assets/stylesheets/application.css
- app/views/resumes/index.html.erb
> [style]: 履歷列表的卡片式排版

- config/locales/zh-TW.yml
> [fix]: i18n translate

- app/views/shared/_navbar.html.erb
> [Fix]: navbar company path

- app/views/companies/_form.html.erb
> [fix]: 在新增公司頁面補上placeholder 
